-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.watchlist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  media_type text NOT NULL CHECK (media_type = ANY (ARRAY['movie'::text, 'tv'::text, 'anime'::text])),
  tmdb_id integer,
  anilist_id integer,
  title text NOT NULL,
  poster_path text,
  overview text,
  release_date text,
  vote_average real,
  total_seasons integer DEFAULT 1,
  total_episodes integer DEFAULT 0,
  current_season integer DEFAULT 1,
  current_episode integer DEFAULT 0,
  status text DEFAULT 'planning'::text CHECK (status = ANY (ARRAY['planning'::text, 'watching'::text, 'completed'::text, 'dropped'::text])),
  rating integer CHECK (rating >= 0 AND rating <= 10),
  notes text,
  started_watching_at timestamp with time zone,
  completed_at timestamp with time zone,
  last_watched_at timestamp with time zone,
  added_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT watchlist_pkey PRIMARY KEY (id),
  CONSTRAINT watchlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.watchlist_episodes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  watchlist_id uuid NOT NULL,
  season_number integer NOT NULL DEFAULT 1,
  episode_number integer NOT NULL,
  tmdb_episode_id integer,
  anilist_episode_id integer,
  title text,
  still_path text,
  overview text,
  vote_average real,
  air_date date,
  runtime integer,
  watched boolean DEFAULT false,
  watched_at timestamp with time zone,
  user_rating integer CHECK (user_rating >= 0 AND user_rating <= 10),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT watchlist_episodes_pkey PRIMARY KEY (id),
  CONSTRAINT watchlist_episodes_watchlist_id_fkey FOREIGN KEY (watchlist_id) REFERENCES public.watchlist(id)
);